### ISSUE TITLE
docker attach

### ISSUE THREAD

**Issue by thdotnet** [malice-plugins/windows-defender#1]
Hi, I'm trying to run this container, however it seems that it can't be attached is that right?

using "docker run -it --name test malice/windows-defender" it just prints the normal output:
```sh
Usage: windows-defender [OPTIONS] COMMAND [arg...]

Malice Windows Defender AntiVirus Plugin

Version: 0.1.0, BuildTime: 20180320

Author:
  blacktop - <https://github.com/blacktop>

Options:
  --verbose, -V          verbose output
  --table, -t            output as Markdown table
  --callback, -c         POST results to Malice webhook [$MALICE_ENDPOINT]
  --proxy, -x            proxy settings for Malice webhook endpoint [$MALICE_PROXY]
  --elasitcsearch value  elasitcsearch address for Malice to store results [$MALICE_ELASTICSEARCH]
  --timeout value        malice plugin timeout (in seconds) (default: 60) [$MALICE_TIMEOUT]
  --help, -h             show help
  --version, -v          print the version

Commands:
  update  Update virus definitions
  web     Create a Windows Defender scan web service
  help    Shows a list of commands or help for one command

Run 'windows-defender COMMAND --help' for more information on a command.
```

even if I run docker ps, it does not show the container id. Am I missing something? 
Thanks in advance

**Comment by blacktop** [comment]
When you say "attached" does that mean you want to run a shell inside the container?  This plugin is meant to be ran like an application not a "vm", which means you shouldn't need to attach.

**Comment by thdotnet** [comment]
I see, yeah I was trying to use a shell. I would like to know how to pass a
file to be scanned. I was trying your samples but it always returned that
the file was not found.

Also I got an error when I tried to run the web server. Is that because I’m
running on docker for windows? Should I create a volume and drop the File
on it?

Thanks for the help in advance.

**Comment by blacktop** [comment]
what is the exact cmd you are running?

**Comment by thdotnet** [comment]
docker run --init --rm malice/windows-defender test.txt 
(also with variations including the path to the file)

**Comment by thdotnet** [comment]
figure it out, the problem was to mount the volume. Thanks
