### ISSUE TITLE
PDF file scanning issue

### ISSUE THREAD

**Issue by louisatbics** [malice-plugins/windows-defender#12]
Hi,
When We scan PDF file, it always says that it has been infected but not actually.
**Docker Result :**
![ScanResultofDockerContainer](https://user-images.githubusercontent.com/38640489/108810409-09aa0f80-75e6-11eb-9111-41434802831f.PNG)

**Actual Defender Result**
![DefenderResult](https://user-images.githubusercontent.com/38640489/108810570-60174e00-75e6-11eb-8d23-d3292c7197f0.PNG)

**Comment by dmytrohridin** [comment]
Hi
I'm facing the same issue
any workaround or info about that?

**Comment by blacktop** [comment]
maybe needs updated definitions try latest
