### ISSUE TITLE
illegal instruction (core dumped)

### ISSUE THREAD

**Issue by DDB-en** [malice-plugins/windows-defender#14]
Hi, I'm using seccomp option with Docker 20.10 but still i cannot scan with avscan:

```
$ lsb_release -a | grep Desc
Description:    Ubuntu 20.04.2 LTS
$ docker -v
Docker version 20.10.8, build 3967b7d
$ grep CONFIG_SECCOMP= /boot/config-$(uname -r)
CONFIG_SECCOMP=y
$ docker container run --rm --security-opt seccomp=seccomp.json -v /malware:/malware malice/windows-defender:update EICAR
time="2021-08-20T18:12:40Z" level=fatal msg="exit status 1" category=av path=/malware/EICAR plugin=windows_defender
$ md5sum seccomp.json
b2791521eac866c0e7c0273d1d135a5f  seccomp.json
$ # running new container and exec bash ...
$ docker container exec -it win_def bash
root@d4214f84fe3b:/malware# md5sum /bin/avscan
1193a6abbbfd6b626ec730d68f846a90  /bin/avscan
root@d4214f84fe3b:/malware# avscan -V EICAR
FATA[0000] signal: illegal instruction (core dumped)     category=av path=/malware/EICAR plugin=windows_defender
```

**Comment by web-engineer** [comment]
Same issue here too...

Works fine using 2020 MBP with same version of docker (machine is an i9) however when used on a CentOS 7 KVM (Xeon processors) I get - exactly the same problem.

Tried publishing a working image locally and pushing to the container storage and using that - but it still does the same.

`time="2022-02-08T15:14:28Z" level=fatal msg="signal: illegal instruction" category=av path=/malware/web_167040008 plugin=windows_defender`

I think this is a CPU related bug - servers setup is -

```
cat /proc/cpuinfo
processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 62
model name	: Intel(R) Xeon(R) CPU E5-2620 v2 @ 2.10GHz
stepping	: 4
microcode	: 0x42e
cpu MHz		: 2100.000
cache size	: 15360 KB
physical id	: 0
siblings	: 1
core id		: 0
cpu cores	: 1
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss syscall nx rdtscp lm constant_tsc arch_perfmon nopl xtopology tsc_reliable nonstop_tsc eagerfpu pni pclmulqdq ssse3 cx16 pcid sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm ssbd ibrs ibpb stibp fsgsbase tsc_adjust smep arat md_clear spec_ctrl intel_stibp flush_l1d arch_capabilities
bogomips	: 4200.00
clflush size	: 64
cache_alignment	: 64
address sizes	: 43 bits physical, 48 bits virtual
power management:
```

I have a feeling defender is using calls that rely on a newer CPU instruction set that isn't present on the cpu I'm using in production - "Intel(R) Xeon(R) CPU E5-2620" and thats where its falling down - but I can't be sure.

Some similar issues on another product noted here - https://discuss.circleci.com/t/all-recent-builds-failing-with-signal-illegal-instruction/17422/2

Guess that means that this project is simply not compatible with this CPU? Or is there something we can do to force compatibility....

**Comment by blacktop** [comment]
try the new version and make sure you read the README and notice the seccomp requirement

**Comment by web-engineer** [comment]
I'll try and schedule this in April to test. Pretty certain we did use  the seccomp profile and that made no differance to the result, we went a different route but would be good to get this working so I've updated our tracker (12481) and will post the results when were back on this - thanks for the update.
