### ISSUE TITLE
After update error "trace/breakpoint trap (core dumped)"

### ISSUE THREAD

**Issue by Rd1997** [malice-plugins/windows-defender#15]
Before update it works fine but once its updated it gives this error 
time="2021-12-23T05:02:05Z" level=fatal msg="signal: trace/breakpoint trap (core dumped)" category=av path=/malware/1cbec920afe2f978b8f84e0a4e6b757d400aeb96e8c0a221130060b196ece010 plugin=windows_defender

**Comment by blacktop** [comment]
This image is possible due to the work of Tavis here https://github.com/taviso/loadlibrary. Is there anything mentioned there that could fix this?

**Comment by Rd1997** [comment]
No but there is one open issue "__rsignal(RSIG_BOOTENGINE) returned failure, missing definitions?" Update after 6, August are giving this issue due the error is seen in  malice-plugins / windows-defender.

Thanks for the support

**Comment by blacktop** [comment]
I would look at "closed" issues as well

**Comment by blacktop** [comment]
try the latest version

**Comment by Rd1997** [comment]
Sure will check 

Thank you
