### ISSUE TITLE
fixing the build and update

### ISSUE THREAD

**Issue by DeDuplicate** [malice-plugins/windows-defender#5]
if you want to fix the update and building the docker file
add in the Dockerfile:
under the RUN add curl installation like that

RUN buildDeps='libreadline-dev:i386 \\
  **curl** \\
  ca-certificates \\
  libc6-dev:i386 \\
  build-essential \\
  gcc-multilib \\
  cabextract \\
  mercurial \\
  git-core \\
  unzip \\
  wget' \\
  && set -x \\
  && dpkg --add-architecture i386 && apt-get update -qq \\
  && apt-get install -y $buildDeps libc6-i386 --no-install-recommends \\
  && echo "===> Install taviso/loadlibrary..." \\
  && git clone https://github.com/taviso/loadlibrary.git /loadlibrary \\
  && echo "===> Download 32-bit antimalware update file.." \\
  && curl -L --output /loadlibrary/engine/mpam-fe.exe "https://www.microsoft.com/security/encyclopedia/adlpackages.aspx?arch=x86" \\
  && cd /loadlibrary/engine \\
  && cabextract mpam-fe.exe \\
  && rm mpam-fe.exe \\
  && cd /loadlibrary \\
  && make -j2 \\
  && echo "===> Clean up unnecessary files..." \\
  && apt-get purge -y --auto-remove $buildDeps $(apt-mark showauto) \\
  && apt-get clean \\
  && rm -rf /var/lib/apt/lists/* /var/cache/apt/archives /tmp/* /var/tmp/*

replace inside the Dockerfile this line:
 && wget --progress=bar:force "https://go.microsoft.com/fwlink/?LinkID=121721&arch=x86" -O \
  /loadlibrary/engine/mpam-fe.exe \

with this line:
&& curl -L --output /loadlibrary/engine/mpam-fe.exe "https://www.microsoft.com/security/encyclopedia/adlpackages.aspx?arch=x86" \

and also go to the **update.sh** file and chenge the line:
apt-get update -qq && apt-get install -yq wget cabextract

to this line:
apt-get update -qq && apt-get install -yq wget cabextract **curl**

and

wget --progress=bar:force "https://go.microsoft.com/fwlink/?LinkID=121721&arch=x86" -O /loadlibrary/engine/mpam-fe.exe

to this line :

curl -L --output /loadlibrary/engine/mpam-fe.exe "https://www.microsoft.com/security/encyclopedia/adlpackages.aspx?arch=x86"

also replace this line:
apt-get purge -y --auto-remove wget cabextract "$(apt-mark showauto)"
apt-get clean \

to this line:
apt-get purge -y --auto-remove wget cabextract curl "$(apt-mark showauto)"
apt-get clean

**Comment by blacktop** [comment]
Many thanks!
