### ISSUE TITLE
Error:Illegal instruction (core dumped)

### ISSUE THREAD

**Issue by Ronniexie** [malice-plugins/windows-defender#6]
I go into the container and  exec "./mpclient /malware/web_423151375"
but something is wrong “Illegal instruction (core dumped)”
Is that the reason？：I use centos to run docker

**Comment by blacktop** [comment]
Did you see this https://github.com/malice-plugins/windows-defender#notice-warning

You need to use the seccomp profile to white-list a required syscall

**Comment by Ronniexie** [comment]
> Did you see this https://github.com/malice-plugins/windows-defender#notice-warning
> 
> You need to use the seccomp profile to white-list a required syscall

we use docker 18.09.8,but there are still the problem.
"FATA[0004] signal: illegal instruction (core dumped)     category=av path=/malware/web_137529060 plugin=windows_defender"

**Comment by tldale** [comment]
I have this same issue with and without the seccomp profile being added. Anything fix this issue?

**Comment by blacktop** [comment]
check out readme notice seccomp
