### ISSUE TITLE
mpclient: function at 0x5a3f5734 attempted to call an unknown symbol

### ISSUE THREAD

**Issue by Ronniexie** [malice-plugins/windows-defender#7]
The new engine version 1.1.17300.4 released 2020-07-30 breaks mpclient, this is the error message:

./mpclient test.txt
mpclient: function at 0x5a3f5734 attempted to call an unknown symbol
Trace/breakpoint trap

**Comment by kscieslinski** [comment]
I've encountered same problem recently. Make sure you newest versions of both `libc6-dev:i386`, `libreadline-dev:i386` installed on your container (apt update && apt upgrade will not be enough).
 
As a quick fix I suggest you just substitute: `FROM ubuntu:bionic` with `FROM ubuntu:focal`.
