### ISSUE TITLE
Calling micro service through rest full api

### ISSUE THREAD

**Issue by louisatbics** [malice-plugins/windows-defender#9]
Hi,

I need to call the defender micro service through rest full API. Could you please guide me on that ?

Thanks & Regards,
Louis

**Comment by kscieslinski** [comment]
https://github.com/malice-plugins/windows-defender/blob/master/docs/web.md

**Comment by louisatbics** [comment]
![Postman_sample](https://user-images.githubusercontent.com/38640489/108809205-4de7e080-75e3-11eb-88d2-557a4803efba.PNG)
